// SPDX-License-Identifier: AGPL-3.0-or-later

package probe

import (
	"context"
	"fmt"
	"regexp"
	"time"
)

// doxygenProbe reads which Doxygen generated a documentation site. Every
// HTML page Doxygen writes says so three times: <meta name="generator"
// content="Doxygen 1.19.0"/>, "<!-- Generated by Doxygen 1.19.0 -->", and
// the footer (confirmed on doxygen.nl's own manual, generated by Doxygen;
// testdata/doxygen_1.19.0_index.html keeps its head and footer). It is the
// version the docs were last built with — what an outdated docs pipeline
// still runs — not a server's. The page read is "/" unless the target's
// path says otherwise (a site served under /docs/, say).
type doxygenProbe struct{}

func (doxygenProbe) Meta() Meta {
	return Meta{
		Product:       "doxygen",
		Summary:       "Doxygen-generated documentation site",
		DefaultScheme: "https",
		Auth:          AuthSpec{Required: false, Kinds: []AuthKind{AuthBasic}},
		// No endoflife.date page; tags are "Release_1_18_0".
		DefaultResolver: ResolverRef{Type: "github", ID: "doxygen/doxygen"},
	}
}

var (
	doxygenGeneratorPattern = regexp.MustCompile(`<meta name="generator" content="Doxygen (\d+(?:\.\d+)+)"`)
	doxygenCommentPattern   = regexp.MustCompile(`<!-- Generated by Doxygen (\d+(?:\.\d+)+) -->`)
)

func (doxygenProbe) Probe(ctx context.Context, t Target) (Observation, error) {
	start := time.Now()
	obs := Observation{
		Kind: "observation", ID: t.ID, Name: t.Name, Product: t.Product,
		CollectedAt: start.UTC(), TLSVerified: Verified(t.Address, t.TLS),
	}

	resp, err := FetchHTTP(ctx, t, Request{Path: "/", Accept: "text/html"})
	if err != nil {
		return obs, err
	}
	defer resp.Body.Close()
	obs.Endpoint = resp.Request.URL.Path
	obs.DurationMS = time.Since(start).Milliseconds()

	body, err := ReadBody(resp)
	if err != nil {
		return obs, err
	}
	for _, p := range []*regexp.Regexp{doxygenGeneratorPattern, doxygenCommentPattern} {
		if m := p.FindSubmatch(body); m != nil {
			obs.Version = string(m[1])
			return obs, nil
		}
	}
	return obs, fmt.Errorf("%w: no Doxygen generator mark on %s (not a Doxygen page, or behind a login)", ErrNotSupported, obs.Endpoint)
}
