// SPDX-License-Identifier: AGPL-3.0-or-later

package probe

import (
	"context"
	"errors"
	"os"
	"path/filepath"
	"testing"
)

// doxygen_1.19.0_index.html is the head and footer of doxygen.nl's own
// manual index, which Doxygen generated.
func TestDoxygenProbeRealFixture(t *testing.T) {
	raw, err := os.ReadFile(filepath.Join("testdata", "doxygen_1.19.0_index.html"))
	if err != nil {
		t.Fatalf("fixture: %v", err)
	}
	obs, err := doxygenProbe{}.Probe(context.Background(), target(pageServer(t, "/", 200, raw), "doxygen"))
	if err != nil || obs.Version != "1.19.0" {
		t.Fatalf("got %q, %v", obs.Version, err)
	}
}

func TestDoxygenProbeCommentOnly(t *testing.T) {
	obs, err := doxygenProbe{}.Probe(context.Background(), target(pageServer(t, "/", 200, []byte("<!-- Generated by Doxygen 1.9.8 -->")), "doxygen"))
	if err != nil || obs.Version != "1.9.8" {
		t.Fatalf("got %q, %v", obs.Version, err)
	}
}

// An SSO sign-in page in front of the docs, for instance.
func TestDoxygenProbeNoMark(t *testing.T) {
	_, err := doxygenProbe{}.Probe(context.Background(), target(pageServer(t, "/", 200, []byte("<html>Sign in</html>")), "doxygen"))
	if !errors.Is(err, ErrNotSupported) {
		t.Fatalf("got %v, want ErrNotSupported", err)
	}
}
